default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pgapp_development2
  host: localhost

test:
  <<: *default
  database: pgapp_test2

production:
  host: localhost
  adapter: postgresql
  username: 
  password: 
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>