default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") %>
  encoding: <%= ENV.fetch("DATABASE_ENCODING") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_DEVELOPMENT") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST") %>

production:
  host: <%= ENV.fetch("DATABASE_HOST") %>
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") %>
  username: 
  password: 
  timeout: <%= ENV.fetch("DATABASE_TIMEOUT") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>