default: &default
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  adapter: postgresql
  username: <%= ENV.fetch("DATABASE_USERNAME") { '' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { '' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST") { '' } %>

production:
  <<: *default
  detabase: <%= ENV.fetch("DATABASE_NAME") { '' } %>
